version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
  pq:
    image: "postgres:alpine"
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_DB=jc
      - POSTGRES_USER=jc
